# Generated by Django 4.1.7 on 2023-04-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sofa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_pessoas', models.IntegerField()),
                ('modelo', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('servicos', models.CharField(max_length=100)),
            ],
        ),
    ]
