# Generated by Django 4.1.7 on 2023-03-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sofa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_pessoas', models.IntegerField()),
                ('modelosofa', models.CharField(max_length=50)),
                ('materialsofa', models.CharField(max_length=50)),
                ('servicosofa', models.CharField(max_length=50)),
            ],
        ),
    ]
