# Generated by Django 4.1.7 on 2023-03-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washBudget', '0002_alter_sofa_materialsofa_alter_sofa_modelosofa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sofa',
            name='materialsofa',
        ),
        migrations.RemoveField(
            model_name='sofa',
            name='modelosofa',
        ),
        migrations.RemoveField(
            model_name='sofa',
            name='servicosofa',
        ),
        migrations.AddField(
            model_name='sofa',
            name='material',
            field=models.CharField(choices=[('tecido', 'Tecido')], default='tecido', max_length=20),
        ),
        migrations.AddField(
            model_name='sofa',
            name='modelo',
            field=models.CharField(choices=[('retratil', 'Sofá Retrátil'), ('comum', 'Sofá Comum'), ('canto', 'Sofá de Canto'), ('chaise', 'Sofá com Chaise'), ('cama', 'Sofá-Cama'), ('cantoalemao', 'Canto Alemão'), ('namoradeira', 'Namoradeira'), ('diva', 'Divã')], default='comum', max_length=20),
        ),
        migrations.AddField(
            model_name='sofa',
            name='servicos',
            field=models.CharField(choices=[('limpeza', 'Limpeza')], default='limpeza', max_length=20),
        ),
        migrations.AlterField(
            model_name='sofa',
            name='num_pessoas',
            field=models.PositiveIntegerField(),
        ),
    ]
