# Generated by Django 4.1.7 on 2023-03-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washBudget', '0003_remove_sofa_materialsofa_remove_sofa_modelosofa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sofa',
            name='num_pessoas',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
