# Generated by Django 4.1.7 on 2023-03-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washBudget', '0004_alter_sofa_num_pessoas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sofa',
            name='material',
            field=models.CharField(choices=[('tecido', 'Tecido')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sofa',
            name='modelo',
            field=models.CharField(choices=[('retratil', 'Sofá Retrátil'), ('comum', 'Sofá Comum'), ('canto', 'Sofá de Canto'), ('chaise', 'Sofá com Chaise'), ('cama', 'Sofá-Cama'), ('cantoalemao', 'Canto Alemão'), ('namoradeira', 'Namoradeira'), ('diva', 'Divã')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sofa',
            name='num_pessoas',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sofa',
            name='servicos',
            field=models.CharField(choices=[('limpeza', 'Limpeza')], max_length=20),
        ),
    ]
