# Generated by Django 4.1.7 on 2023-03-27 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washBudget', '0005_alter_sofa_material_alter_sofa_modelo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sofa',
            name='num_pessoas',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2)]),
        ),
    ]
