# Generated by Django 4.1.7 on 2023-03-27 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('washBudget', '0006_alter_sofa_num_pessoas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sofa',
        ),
    ]
